name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p build

      - name: Ensure images directory exists
        run: mkdir -p images

      - name: Download headshot from Google Drive
        run: |
          # Install required tool for downloading
          sudo apt-get update && sudo apt-get install -y wget curl
          
          # Download the image using the secret URL
          curl -L "${{ secrets.HEADSHOT_URL }}" -o "images/headshot.JPG"
      
      - name: Copy files for deployment
        run: |
          # Copy everything except the images folder
          rsync -av --exclude='images' --exclude='.git' --exclude='.github' . build/
          # Create an empty images folder in build
          mkdir -p build/images
          # Copy any other images you want to include (but not headshot)
          # cp images/other-public-image.jpg build/images/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # Deploy only the build folder
          branch: gh-pages  # The branch the action should deploy to
          clean: true  # Automatically remove deleted files from the deploy branch
          single-commit: true  # Make a single commit with all changes
